-- ============================================================================
-- 02_RAW_TABLES.SQL - Domain-specific typed table schemas
-- ============================================================================
USE DATABASE BANKING_MICROINSURANCE;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.BRANCHES (
  BRANCH_ID VARCHAR(20) NOT NULL, BRANCH_NAME VARCHAR(200), CITY VARCHAR(50), REGION VARCHAR(50), BRANCH_TYPE VARCHAR(30), EMPLOYEES INT, OPENED_DATE DATE, DIGITAL_ENABLED BOOLEAN, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.ACCOUNTS (
  ACCOUNT_ID VARCHAR(20) NOT NULL, ACCOUNT_NAME VARCHAR(200), ACCOUNT_TYPE VARCHAR(30), REGION VARCHAR(50), BALANCE FLOAT, PROFIT_RATE FLOAT, STATUS VARCHAR(20), OPENED_DATE DATE, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.TRANSACTIONS (
  TXN_ID VARCHAR(30) NOT NULL, ACCOUNT_ID VARCHAR(20), TXN_TYPE VARCHAR(30), AMOUNT FLOAT, CURRENCY VARCHAR(5), COUNTERPARTY VARCHAR(100), TXN_DATE TIMESTAMP, STATUS VARCHAR(20), CHANNEL VARCHAR(30), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.LOANS (
  LOAN_ID VARCHAR(30) NOT NULL, BRANCH_ID VARCHAR(20), CUSTOMER_ID VARCHAR(20), LOAN_TYPE VARCHAR(30), PRINCIPAL FLOAT, INTEREST_RATE FLOAT, TENOR_MONTHS INT, DISBURSEMENT_DATE DATE, STATUS VARCHAR(20), DPD INT, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
