-- Generated from generator/demo_specs/aws-philippines-banking-microinsurance.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-philippines-banking-microinsurance
-- This is the schema that is actually deployed for PH_BANKING_MICROINSURANCE.

-- Alerts fire on the bottom tail of Claims Ratio
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_CLAIMS_RATIO) AS T
  FROM RAW.POLICIES
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_CLAIMS_RATIO <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_CLAIMS_RATIO), 2) AS AVG_CLAIMS_RATIO,
  ROUND(AVG(f.KPI_PREMIUM_INCOME), 2) AS AVG_PREMIUM_INCOME,
  ROUND(AVG(f.KPI_DIGITAL_ENROLLMENT), 2) AS AVG_DIGITAL_ENROLLMENT,
  ROUND(AVG(f.KPI_RENEWAL_RATE), 2) AS AVG_RENEWAL_RATE
FROM RAW.POLICIES f
JOIN RAW.PRODUCTS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_CLAIMS_RATIO), 2) AS AVG_CLAIMS_RATIO,
  ROUND(AVG(f.KPI_PREMIUM_INCOME), 2) AS AVG_PREMIUM_INCOME,
  ROUND(AVG(f.KPI_DIGITAL_ENROLLMENT), 2) AS AVG_DIGITAL_ENROLLMENT,
  ROUND(AVG(f.KPI_RENEWAL_RATE), 2) AS AVG_RENEWAL_RATE
FROM RAW.POLICIES f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_CLAIMS_RATIO) AS KPI_CLAIMS_RATIO, AVG(KPI_PREMIUM_INCOME) AS KPI_PREMIUM_INCOME, AVG(KPI_DIGITAL_ENROLLMENT) AS KPI_DIGITAL_ENROLLMENT, AVG(KPI_RENEWAL_RATE) AS KPI_RENEWAL_RATE FROM RAW.POLICIES),
     en AS (SELECT SUM(KPI_POLICIES_ACTIVE) AS KPI_POLICIES_ACTIVE, SUM(KPI_INCLUSION_REACH) AS KPI_INCLUSION_REACH, SUM(KPI_AGENT_NETWORK) AS KPI_AGENT_NETWORK FROM RAW.PRODUCTS)
  SELECT 1 AS SORT_ORDER, 'Policies Active' AS TITLE, KPI_POLICIES_ACTIVE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_POLICIES_ACTIVE) / 1000000), 1) AS DECIMAL(38,1))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Claims Ratio' AS TITLE, KPI_CLAIMS_RATIO AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CLAIMS_RATIO)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Premium Income' AS TITLE, KPI_PREMIUM_INCOME AS VALUE_NUM, 'PHP' || ' ' || TO_VARCHAR(CAST(ROUND(((KPI_PREMIUM_INCOME) / 1000000000), 1) AS DECIMAL(38,1))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Inclusion Reach' AS TITLE, KPI_INCLUSION_REACH AS VALUE_NUM, '+' || TO_VARCHAR(CAST(ROUND(((KPI_INCLUSION_REACH) / 1000000), 1) AS DECIMAL(38,1))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Agent Network' AS TITLE, KPI_AGENT_NETWORK AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_AGENT_NETWORK) / 1000)) AS DECIMAL(38,0))) || 'K' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Digital Enrollment' AS TITLE, KPI_DIGITAL_ENROLLMENT AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_DIGITAL_ENROLLMENT)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Renewal Rate' AS TITLE, KPI_RENEWAL_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_RENEWAL_RATE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
