-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Microinsurance Claims Analytics & Fraud Detection
-- ============================================================================
USE DATABASE MICROINSURANCE;
USE SCHEMA ML;

-- ML.CLASSIFICATION: FRAUD_DETECTOR
CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION ML.FRAUD_DETECTOR(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.FRAUD_INDICATORS'),
  TARGET_COLNAME => 'IS_FRAUDULENT'
);

-- ML.CLASSIFICATION: AUTO_ADJUDICATION
CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION ML.AUTO_ADJUDICATION(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.CLAIMS_ENRICHED'),
  TARGET_COLNAME => 'APPROVAL_DECISION'
);

