-- ============================================================================
-- 99_RESET.SQL — Reset Microinsurance Claims Analytics & Fraud Detection to clean demo state
-- ============================================================================
USE DATABASE MICROINSURANCE;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_PARSE_DOCUMENTS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_SCORE_CLAIMS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_ALERT_INVESTIGATORS SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.CLAIMS_ENRICHED REFRESH;
ALTER DYNAMIC TABLE CURATED.FRAUD_INDICATORS REFRESH;
ALTER DYNAMIC TABLE CURATED.LOSS_RATIO_ANALYSIS REFRESH;
ALTER DYNAMIC TABLE CURATED.PROCESSING_METRICS REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM MICROINSURANCE.RAW.CLAIMS → 185000
-- SELECT COUNT(*) FROM MICROINSURANCE.RAW.CLAIM_DOCUMENTS → 520000
-- SELECT COUNT(*) FROM MICROINSURANCE.CURATED.CLAIMS_ENRICHED WHERE AUTO_ADJUDICATED = TRUE → ~114700

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_ALERT_INVESTIGATORS RESUME;
ALTER TASK IF EXISTS APP.TASK_SCORE_CLAIMS RESUME;
ALTER TASK IF EXISTS APP.TASK_PARSE_DOCUMENTS RESUME;
